#include <iomanip>
#include <iostream>
#include <vector>
#include <string>
#include <time.h>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <chrono>
#include <deque>
#include <list>
#include <regex>

using std::sregex_iterator;
using std::regex;
using std::stable_sort;
using std::partition;
using std::stable_sort;
using std::move;
using std::next;
using std::deque;
using std::list;
using std::istringstream;
using std::chrono::high_resolution_clock;
using std::chrono::duration_cast;
using std::chrono::microseconds;
using std::to_string;
using std::stringstream;
using std::ifstream;
using std::ofstream;
using std::cin;
using std::cout;
using std::setw;
using std::setprecision;
using std::vector;
using std::string;
using std::endl;
using std::_Char_traits;
using std::left;
using std::copy;
using std::copy_n;
using std::numeric_limits;
using std::streamsize;
using std::sort;
using std::fixed;

